import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import "./globals.css";
import Nav from "@/components/Navbar";
import { NextIntlClientProvider, useMessages } from "next-intl";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Project Mau(Cat sterilizations initiative)",
  description: "Generated by create next app",
};

interface RootLayoutProps{
  children: React.ReactNode;
  params:{
    locale:string;
  };
}

export default function RootLayout({
  children,
  params:{ locale },
}: Readonly<RootLayoutProps>) {
  const messages = useMessages();
  

    return (
    <html lang={locale}>
      <body className={inter.className}>
      <NextIntlClientProvider locale={locale} messages={messages}>
        <Nav/>
        <div className="background-container">{children}</div>
        <Footer/>
        </NextIntlClientProvider>
      </body>
    </html>);
}